# Generated by Django 4.2.14 on 2024-08-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
